{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llm-inference.fullname" . }}
  labels:
    {{- include "llm-inference.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "llm-inference.selectorLabels" . | nindent 6 }}
{{- end }}
